(function(){'use strict';
var e="object"===typeof __ScalaJSEnv&&__ScalaJSEnv?__ScalaJSEnv:{},h="object"===typeof e.global&&e.global?e.global:"object"===typeof global&&global&&global.Object===Object?global:this;e.global=h;e.exportsNamespace="object"===typeof e.exportsNamespace&&e.exportsNamespace?e.exportsNamespace:h;h.Object.freeze(e);var aa={envInfo:e,semantics:{asInstanceOfs:2,arrayIndexOutOfBounds:2,moduleInit:2,strictFloats:!1,productionMode:!0},assumingES6:!1,linkerVersion:"0.6.22",globalThis:this};h.Object.freeze(aa);
h.Object.freeze(aa.semantics);var ba=h.Math.imul||function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0},m=h.Math.clz32||function(a){if(0===a)return 32;var b=1;0===(a&4294901760)&&(a<<=16,b+=16);0===(a&4278190080)&&(a<<=8,b+=8);0===(a&4026531840)&&(a<<=4,b+=4);0===(a&3221225472)&&(a<<=2,b+=2);return b+(a>>31)},n=0,p=h.WeakMap?new h.WeakMap:null;function q(a){return function(b,c){return!(!b||!b.$classData||b.$classData.k!==c||b.$classData.i!==a)}}
function ca(a){for(var b in a)return b}function da(a,b,c){var d=new a.y(b[c]);if(c<b.length-1){a=a.m;c+=1;for(var f=d.B,g=0;g<f.length;g++)f[g]=da(a,b,c)}return d}function ea(a){switch(typeof a){case "string":return r(u);case "number":var b=a|0;return b===a?fa(b)?r(ga):ha(b)?r(ia):r(ja):"number"===typeof a?r(ka):r(la);case "boolean":return r(ma);case "undefined":return r(na);default:return null===a?a.la():a&&a.$classData&&a.$classData.f.A?r(oa):a&&a.$classData?r(a.$classData):null}}
function pa(a){switch(typeof a){case "string":qa||(qa=(new v).b());for(var b=0,c=1,d=-1+(a.length|0)|0;0<=d;)b=b+ba(65535&(a.charCodeAt(d)|0),c)|0,c=ba(31,c),d=-1+d|0;return b;case "number":w||(w=(new x).b());b=w;c=a|0;if(c===a&&-Infinity!==1/a)b=c;else{if(b.g)b.F[0]=a,b=y(b.s[b.I]|0,b.s[b.G]|0);else{if(a!==a)b=!1,a=2047,c=+h.Math.pow(2,51);else if(Infinity===a||-Infinity===a)b=0>a,a=2047,c=0;else if(0===a)b=-Infinity===1/a,c=a=0;else if(d=(b=0>a)?-a:a,d>=+h.Math.pow(2,-1022)){a=+h.Math.pow(2,52);
var c=+h.Math.log(d)/.6931471805599453,c=+h.Math.floor(c)|0,c=1023>c?c:1023,f=+h.Math.pow(2,c);f>d&&(c=-1+c|0,f/=2);f=d/f*a;d=+h.Math.floor(f);f-=d;d=.5>f?d:.5<f?1+d:0!==d%2?1+d:d;2<=d/a&&(c=1+c|0,d=1);1023<c?(c=2047,d=0):(c=1023+c|0,d-=a);a=c;c=d}else a=d/+h.Math.pow(2,-1074),c=+h.Math.floor(a),d=a-c,a=0,c=.5>d?c:.5<d?1+c:0!==c%2?1+c:c;c=+c;b=y(c|0,(b?-2147483648:0)|(a|0)<<20|c/4294967296|0)}b=b.t^b.r}return b;case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&a.$classData||
null===a?a.z():null===p?42:ra(a)}}function ta(a,b){var c=h.Object.getPrototypeOf,d=h.Object.getOwnPropertyDescriptor;for(a=c(a);null!==a;){var f=d(a,b);if(void 0!==f)return f;a=c(a)}}function ua(a,b,c){a=ta(a,c);if(void 0!==a)return c=a.get,void 0!==c?c.call(b):a.value}function va(a,b,c,d){a=ta(a,c);if(void 0!==a&&(a=a.set,void 0!==a)){a.call(b,d);return}throw new h.TypeError("super has no setter '"+c+"'.");}
var ra=null!==p?function(a){switch(typeof a){case "string":case "number":case "boolean":case "undefined":return pa(a);default:if(null===a)return 0;var b=p.get(a);void 0===b&&(n=b=n+1|0,p.set(a,b));return b}}:function(a){if(a&&a.$classData){var b=a.$idHashCode$0;if(void 0!==b)return b;if(h.Object.isSealed(a))return 42;n=b=n+1|0;return a.$idHashCode$0=b}return null===a?0:pa(a)};function fa(a){return"number"===typeof a&&a<<24>>24===a&&1/a!==1/-0}
function ha(a){return"number"===typeof a&&a<<16>>16===a&&1/a!==1/-0}function z(){this.u=this.y=void 0;this.i=this.m=this.f=null;this.k=0;this.D=null;this.q="";this.c=this.o=this.p=void 0;this.name="";this.isRawJSType=this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}function A(a,b,c){var d=new z;d.f={};d.m=null;d.D=a;d.q=b;d.c=function(){return!1};d.name=c;d.isPrimitive=!0;d.isInstance=function(){return!1};return d}
function B(a,b,c,d,f,g,l){var k=new z,t=ca(a);g=g||function(a){return!!(a&&a.$classData&&a.$classData.f[t])};l=l||function(a,b){return!!(a&&a.$classData&&a.$classData.k===b&&a.$classData.i.f[t])};k.u=f;k.f=c;k.q="L"+b+";";k.c=l;k.name=b;k.isInterface=!1;k.isRawJSType=!!d;k.isInstance=g;return k}
function wa(a){function b(a){if("number"===typeof a){this.B=Array(a);for(var b=0;b<a;b++)this.B[b]=f}else this.B=a}var c=new z,d=a.D,f="longZero"==d?C().w:d;b.prototype=new D;b.prototype.constructor=b;b.prototype.$classData=c;var d="["+a.q,g=a.i||a,l=a.k+1;c.y=b;c.u=xa;c.f={a:1,oa:1,d:1};c.m=a;c.i=g;c.k=l;c.D=null;c.q=d;c.p=void 0;c.o=void 0;c.c=void 0;c.name=d;c.isPrimitive=!1;c.isInterface=!1;c.isArrayClass=!0;c.isInstance=function(a){return g.c(a,l)};return c}
function r(a){if(!a.p){var b=new E;b.n=a;a.p=b}return a.p}function ya(a){a.o||(a.o=wa(a));return a.o}z.prototype.getFakeInstance=function(){return this===u?"some string":this===ma?!1:this===ga||this===ia||this===ja||this===ka||this===la?0:this===oa?C().w:this===na?void 0:{$classData:this}};z.prototype.getSuperclass=function(){return this.u?r(this.u):null};z.prototype.getComponentType=function(){return this.m?r(this.m):null};
z.prototype.newArrayOfThisClass=function(a){for(var b=this,c=0;c<a.length;c++)b=ya(b);return da(b,a,0)};var za=A(!1,"Z","boolean"),Aa=A(0,"C","char"),Ba=A(0,"B","byte"),Ca=A(0,"S","short"),Da=A(0,"I","int"),Ea=A("longZero","J","long"),Fa=A(0,"F","float"),Ga=A(0,"D","double");za.c=q(za);Aa.c=q(Aa);Ba.c=q(Ba);Ca.c=q(Ca);Da.c=q(Da);Ea.c=q(Ea);Fa.c=q(Fa);Ga.c=q(Ga);function F(){}function D(){}D.prototype=F.prototype;F.prototype.b=function(){return this};F.prototype.v=function(){var a=ea(this).n.name,b=(+(this.z()>>>0)).toString(16);return a+"@"+b};F.prototype.z=function(){return ra(this)};F.prototype.toString=function(){return this.v()};var xa=B({a:0},"java.lang.Object",{a:1},void 0,void 0,function(a){return null!==a},function(a,b){if(a=a&&a.$classData){var c=a.k||0;return!(c<b)&&(c>b||!a.i.isPrimitive)}return!1});F.prototype.$classData=xa;function G(){}
G.prototype=new D;G.prototype.constructor=G;G.prototype.b=function(){return this};G.prototype.$classData=B({O:0},"sjsbtm.HWApp.HWApp$",{O:1,a:1});var Ha=void 0;function E(){this.n=null}E.prototype=new D;E.prototype.constructor=E;E.prototype.v=function(){return(this.n.isInterface?"interface ":this.n.isPrimitive?"":"class ")+this.n.name};E.prototype.$classData=B({V:0},"java.lang.Class",{V:1,a:1});function H(){this.E=this.J=null}H.prototype=new D;H.prototype.constructor=H;
H.prototype.b=function(){I=this;this.J=Ia(!1);this.E=Ia(!0);return this};H.prototype.$classData=B({ca:0},"java.lang.System$",{ca:1,a:1});var I=void 0;function Ja(){I||(I=(new H).b());return I}function J(){}J.prototype=new D;J.prototype.constructor=J;function Ka(){}Ka.prototype=J.prototype;function K(){this.C=null}K.prototype=new D;K.prototype.constructor=K;K.prototype.v=function(){return"DynamicVariable("+this.C+")"};function L(a,b){a.C=b;return a}
K.prototype.$classData=B({ea:0},"scala.util.DynamicVariable",{ea:1,a:1});function x(){this.g=!1;this.F=this.s=this.j=null;this.x=!1;this.I=this.G=0}x.prototype=new D;x.prototype.constructor=x;
x.prototype.b=function(){w=this;this.j=(this.g=!!(h.ArrayBuffer&&h.Int32Array&&h.Float32Array&&h.Float64Array))?new h.ArrayBuffer(8):null;this.s=this.g?new h.Int32Array(this.j,0,2):null;this.g&&new h.Float32Array(this.j,0,2);this.F=this.g?new h.Float64Array(this.j,0,1):null;if(this.g)this.s[0]=16909060,a=1===((new h.Int8Array(this.j,0,8))[0]|0);else var a=!0;this.G=(this.x=a)?0:1;this.I=this.x?1:0;return this};x.prototype.$classData=B({fa:0},"scala.scalajs.runtime.Bits$",{fa:1,a:1});var w=void 0;
function v(){}v.prototype=new D;v.prototype.constructor=v;v.prototype.b=function(){return this};v.prototype.$classData=B({ha:0},"scala.scalajs.runtime.RuntimeString$",{ha:1,a:1});var qa=void 0;function M(){}M.prototype=new D;M.prototype.constructor=M;function La(){}La.prototype=M.prototype;var na=B({ia:0},"scala.runtime.BoxedUnit",{ia:1,a:1,d:1},void 0,void 0,function(a){return void 0===a}),ma=B({T:0},"java.lang.Boolean",{T:1,a:1,d:1,e:1},void 0,void 0,function(a){return"boolean"===typeof a});
function N(){this.K=null}N.prototype=new Ka;N.prototype.constructor=N;N.prototype.b=function(){O=this;this.K=L(new K,Ja().J);L(new K,Ja().E);L(new K,null);return this};N.prototype.$classData=B({da:0},"scala.Console$",{da:1,pa:1,a:1,ra:1});var O=void 0;function P(){this.w=null}P.prototype=new D;P.prototype.constructor=P;P.prototype.b=function(){Q=this;this.w=y(0,0);return this};
function Ma(a,b){if(0===(-2097152&b))b=""+(4294967296*b+ +(a>>>0));else{var c=(32+m(1E9)|0)-(0!==b?m(b):32+m(a)|0)|0,d=c,f=0===(32&d)?1E9<<d:0,d=0===(32&d)?5E8>>>(31-d|0)|0|0<<d:1E9<<d,g=a,l=b;for(a=b=0;0<=c&&0!==(-2097152&l);){var k=g,t=l,Oa=f,sa=d;if(t===sa?(-2147483648^k)>=(-2147483648^Oa):(-2147483648^t)>=(-2147483648^sa))k=l,t=d,l=g-f|0,k=(-2147483648^l)>(-2147483648^g)?-1+(k-t|0)|0:k-t|0,g=l,l=k,32>c?b|=1<<c:a|=1<<c;c=-1+c|0;k=d>>>1|0;f=f>>>1|0|d<<31;d=k}c=l;if(0===c?-1147483648<=(-2147483648^
g):-2147483648<=(-2147483648^c))c=4294967296*l+ +(g>>>0),g=c/1E9,f=g/4294967296|0,d=b,b=g=d+(g|0)|0,a=(-2147483648^g)<(-2147483648^d)?1+(a+f|0)|0:a+f|0,g=c%1E9|0;c=""+g;b=""+(4294967296*a+ +(b>>>0))+"000000000".substring(c.length|0)+c}return b}P.prototype.$classData=B({ga:0},"scala.scalajs.runtime.RuntimeLong$",{ga:1,a:1,qa:1,d:1});var Q=void 0;function C(){Q||(Q=(new P).b());return Q}function R(){}R.prototype=new D;R.prototype.constructor=R;function S(){}S.prototype=R.prototype;
var u=B({P:0},"java.lang.String",{P:1,a:1,d:1,na:1,e:1},void 0,void 0,function(a){return"string"===typeof a}),ga=B({U:0},"java.lang.Byte",{U:1,h:1,a:1,d:1,e:1},void 0,void 0,function(a){return fa(a)}),la=B({W:0},"java.lang.Double",{W:1,h:1,a:1,d:1,e:1},void 0,void 0,function(a){return"number"===typeof a}),ka=B({X:0},"java.lang.Float",{X:1,h:1,a:1,d:1,e:1},void 0,void 0,function(a){return"number"===typeof a}),ja=B({Y:0},"java.lang.Integer",{Y:1,h:1,a:1,d:1,e:1},void 0,void 0,function(a){return"number"===
typeof a&&(a|0)===a&&1/a!==1/-0}),oa=B({aa:0},"java.lang.Long",{aa:1,h:1,a:1,d:1,e:1},void 0,void 0,function(a){return!!(a&&a.$classData&&a.$classData.f.A)}),ia=B({ba:0},"java.lang.Short",{ba:1,h:1,a:1,d:1,e:1},void 0,void 0,function(a){return ha(a)});function T(){this.r=this.t=0}T.prototype=new La;T.prototype.constructor=T;T.prototype.v=function(){C();var a=this.t,b=this.r;return b===a>>31?""+a:0>b?"-"+Ma(-a|0,0!==a?~b:-b|0):Ma(a,b)};function y(a,b){var c=new T;c.t=a;c.r=b;return c}
T.prototype.z=function(){return this.t^this.r};T.prototype.$classData=B({A:0},"scala.scalajs.runtime.RuntimeLong",{A:1,h:1,a:1,d:1,e:1});function U(){}U.prototype=new S;U.prototype.constructor=U;function Na(){}Na.prototype=U.prototype;U.prototype.Q=function(){return this};function V(){}V.prototype=new S;V.prototype.constructor=V;V.prototype.b=function(){return this};V.prototype.$classData=B({$:0},"java.lang.JSConsoleBasedPrintStream$DummyOutputStream",{$:1,N:1,a:1,L:1,S:1,M:1});function W(){}
W.prototype=new Na;W.prototype.constructor=W;function Pa(){}Pa.prototype=W.prototype;W.prototype.R=function(){U.prototype.Q.call(this);return this};function X(){this.l=this.H=null}X.prototype=new Pa;X.prototype.constructor=X;function Ia(a){var b=new X;b.H=a;(new V).b();W.prototype.R.call(b);b.l="";return b}X.prototype.$classData=B({Z:0},"java.lang.JSConsoleBasedPrintStream",{Z:1,ka:1,ja:1,N:1,a:1,L:1,S:1,M:1,ma:1});Ha||(Ha=(new G).b());new (ya(u).y)([]);O||(O=(new N).b());
for(var Y=O.K.C,Z="Hello from HWApp\n";""!==Z;){var Qa=Z.indexOf("\n")|0;if(0>Qa)Y.l=""+Y.l+Z,Z="";else{var Ra=""+Y.l+Z.substring(0,Qa);h.console&&(Y.H&&h.console.error?h.console.error(Ra):h.console.log(Ra));Y.l="";Z=Z.substring(1+Qa|0)}};
}).call(this);
//# sourceMappingURL=out.js.map
